# Generated by Django 3.2.4 on 2022-03-03 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_backend', '0002_auto_20220303_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation', models.ForeignKey(db_column='conversationId', on_delete=django.db.models.deletion.CASCADE, related_name='conversation_groups', related_query_name='conversation_group', to='messenger_backend.conversation')),
                ('userId', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='messenger_backend.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
