# Generated by Django 3.2.4 on 2022-02-27 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_backend', '0002_message_isunread'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='isUnread',
        ),
    ]
