# Generated by Django 3.2.4 on 2022-03-04 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_backend', '0005_alter_conversationgroup_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationgroup',
            name='userId',
            field=models.IntegerField(),
        ),
    ]
