# Generated by Django 3.2.4 on 2022-03-04 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_backend', '0006_alter_conversationgroup_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationgroup',
            name='userId',
            field=models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='users', to='messenger_backend.user'),
        ),
    ]
