# Generated by Django 3.2.4 on 2022-03-06 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_backend', '0007_alter_conversationgroup_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversationgroup',
            old_name='userId',
            new_name='user',
        ),
    ]
